
development:
  adapter: postgresql
  encoding: unicode
  database: db/rem
  pool: 5
  timeout: 5000
  username: postgres
  password: 123

test:
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 5
  timeout: 5000
  username: postgres
  password: 123
